import { Geist, Geist_Mono, Libre_Baskerville } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";

const libre = Libre_Baskerville({
  subsets: ["latin"],
  weight: ["400", "700"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Fitness Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${libre.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <main>
          {children}
        </main>
        <ToastContainer />
      </body>
    </html>
  );
}
